version: 2.1

orbs:
  node: circleci/node@4.0.0

jobs:
  test:
    machine:
      image: 'circleci/classic:latest'
    parameters:
      browser:
        type: string
        default: chrome
    steps:
      - checkout
      - run:
          name: Build souce code & compile test project
          command: docker-compose run --rm gondola.builder
          working_directory: webpage
      - run:
          name: run all tests
          command: docker-compose run --rm gondola.tester
          working_directory: webpage
          environment:
            BROWSER: << parameters.browser >>
      - store_test_results:
          path: webpage/results/
      - store_artifacts:
          path: webpage/results/
          destination: results

workflows:
  test:
    jobs:
      - test:
          context: Gondola License
          matrix:
            parameters:
              browser:
                - chrome
                - firefox
